### ISSUE TITLE
Playlists support

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-media-sensors#25]
It looks like Kodi supports fetching user playlists and then playing them from the JSON-RPC interface: https://forum.kodi.tv/showthread.php?tid=299022

It would be great if I could have an interface that lets me select a user playlist for playback, in addition to letting me modify the ongoing playlist.  Thanks!

**Comment by jtbgroup** [comment]
Hi Rudd-O,

If I understand well, you have playlists defined in kodi and you want to be able to select one of them directly from the card? Personally, I do that in a script + a button. This is what the script looks like (playlist is played in party mode):
``` yaml
vds_pu_kodi_playlist_quiet:
  alias: ''
  sequence:
    - alias: 'Playlist Quiet'
      data:
        entity_id: !secret GLOB_ENTITY_ID_KODI
        method: Player.Open
        item: {"partymode": "special://profile/playlists/music/Playlist Quiet.xsp"}
      service: kodi.call_method
```

And I use the mini-player card for the buttons:
![image](https://user-images.githubusercontent.com/10096931/211071734-4d9b8593-4be8-41e4-9587-a2e57de7fe53.png)

Of course this is possible with only a few playlists. I will something in the card, but I can't promise the result will be clean. I keep you posted.
